# Lab 0: Introduction to Python 

## Exercise 1: Defining Variables (8 pts)  
1. Create 4 scalar variables `a,b,c,d` containing the values 1,2,3,4.  

In [10]:
a = 1
b = 2 
c = 3 
d = 4

2. Define a 3-component horizontal vector `H` containing `a,b,c`.  

In [11]:
import numpy as np 

H = np.array([a,b,c])

3. Define a 3-component vertical vector `V` containing `b,c,d`.  

In [3]:
V = np.array([b,c,d]).reshape(-1,1)

4. Define a 2x2 matric `M` containing a,b,c,d as:  
$$ M = \begin{pmatrix} a & b \\ c & d \end{pmatrix} $$  

In [4]:
M = np.array([[a,b],[c,d]])

5. Displace the values of:  
  a. The third element of `H`  
  b. The first element of `V`  
  c. The first row of `M`  
  d. The second column of `M`

In [5]:
print('a. The third element of H:', H[2])
print('b. The first element of V:', V[0])
print('c. The third element of H:', M[0,:])
print('d. The third element of H:', M[:,1])

a. The third element of H: 3
b. The first element of V: [2]
c. The third element of H: [1 2]
d. The third element of H: [2 4]


## Exercise 2: Vector Math (15 points)  

1. Using the variable you defined in Exercise 1, complete each of the following operations. 
Next to the operation comment on if the operation is defined. If the operation is not defined,
comment out the line so your code continues running without an error and state why the operation is not valid. 
I have provided you with two examples to demonstrate formatting.  

  a. `a+b`  
  b. `V+H`  
  c. `H+M`  
  d. `H+H`  
  e. `b+M`  
  f. `b*d`  
  g. `V.*V`  
  h. `V*V`  
  i. `V*H`   
  j. `H*V`    
  k. `V.*H`    
  l. `H.*V`  
  m. `d*M`  
  n. `M*H`  
  o. `M.*H`  
  p. `M*M`  
  
2. What is the size of `V@H`?  What are the two ways you can find the shape of the variable? (_hint_ : One is globally defined function and one is an attribute of `numpy` arrays.)  

3. What the difference between the `@` and `*` operators? 

In [32]:
#a
a + b

3

In [33]:
#b
V+H

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [39]:
#c 
# H+M # Undefined, because the shapes do not match

In [35]:
#d 
H+H

array([2, 4, 6])

In [37]:
#e
b+M

array([[3, 4],
       [5, 6]])

In [38]:
#f 
b*d

8

In [40]:
#g
V*V

array([[ 4],
       [ 9],
       [16]])

In [43]:
#h
#V@V

In [46]:
#i 
#V@H

In [47]:
#j
H@V

array([20])

In [48]:
#k
V*H

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [49]:
#l
H*V

array([[ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [50]:
#m
d*M

array([[ 4,  8],
       [12, 16]])

In [56]:
#n
# M@H #undedifneds

In [55]:
#o
# M*H #undedifneds

In [54]:
#p
M@M

array([[ 7, 10],
       [15, 22]])

# Exercise  3: Functions (7 points) 

Write a function that calculates the distance between two vectors in the form $R(\vec x, \vec y)$. Where $R$ is a function that takes two vectors (i.e. $\vec x$,$\vec y$) as input a returns a scalar value of distance. Use your function to calculate the distance between the follow vector pairs:  
  1. `x = [3, 5]`, `y = [3, 4]`  
  2. `x = [2, 0]`, `y = [0, 2]`  
  3. `x = [-100, 30]`, `y = [-10, -50]` 
  
Hint: [mathematical formula to use](http://mathonline.wikidot.com/the-distance-between-two-vectors).

In [15]:
def R(x,y):
    '''Returns the distance between two vectors of length 2. 

            Parameters:
                    x (array): A vector of length 2
                    y (array): Another vector of length 2

            Returns:
                    distance (float): The distance between the two input vectors
    '''
    return np.sqrt(sum((x - y)**2))

In [16]:
# 1. 
assert R(np.array([3,5]),np.array([3,4])) == 1.0

In [18]:
#2. 
assert R(np.array([3,5]),np.array([3,4])) == 1.0
assert np.round(R(np.array([2,0]),np.array([0,2])),4) == 2.8284

In [22]:
#3. 
assert R(np.array([3,5]),np.array([3,4]))                     == 1.0
assert np.round(R(np.array([2,0]),np.array([0,2])),4)         == 2.8284
assert np.round(R(np.array([-100,30]),np.array([-10,-50])),4) == 120.4159

## Bonus : (3 points)  
Can you "vectorize" (i.e. use element-wise vector operations to simplify) this function? 