# Welcome to `Python` (Part 2)!

We are going to focus on data structures in this notebook. 

# Lists (`list()`)

Lists are mutable (i.e. editable). 

In [33]:
# Define our Grocery List
grocery_list = ['Milk', 'Eggs', 'Bread']

# Print the datatype of our Grocery List
print('grocery_list is of type ', type(grocery_list))

# Print the items in our Grocery List
print('The groceries I need are:', grocery_list)

grocery_list is of type  <class 'list'>
The groceries I need are: ['Milk', 'Eggs', 'Bread']


In [34]:
# Add a item to our list, via the .append() method
grocery_list.append('Beer')

# Print the items in our updated Grocery List
print(grocery_list)

['Milk', 'Eggs', 'Bread', 'Beer']


In [35]:
# Check the number of times (i.e. .count()) an item appears in our list
grocery_list.count('Milk')

1

In [37]:
# Swap the order of elements list to reflect their priority
grocery_list[0]  = 'Beer'
grocery_list[-1] = 'Milk'

# Print the items in our Grocery List not order by priority
print(grocery_list)

['Beer', 'Eggs', 'Bread', 'Milk']


# Tuples (`tuple()`)

A `tuple` is very similar to lists but immutable and defined within `()` instead of `[]`. 

In [40]:
# Define our Grocery Set
grocery_set = ('Milk', 'Eggs', 'Bread')

# Print the datatype of our Grocery List
print('grocery_list is of type ', type(grocery_set))

# Print the items in our Grocery List
print('The groceries I need are:', grocery_set)

grocery_list is of type  <class 'tuple'>
The groceries I need are: ('Milk', 'Eggs', 'Bread')


In [43]:
# Add a item to our list, via the .append() method
grocery_set.append('Beer')

# Print the items in our updated Grocery List
print(grocery_set)

AttributeError: 'tuple' object has no attribute 'append'

In [41]:
groceries[0]  = 'Beer'
groceries[-1] = 'Milk'
print(groceries)

TypeError: 'tuple' object does not support item assignment

# Dictionaries  (`dict()`)

A `dictionary` is very use full data structure, that contains data linked via _keys_. Dictionaries are mutable, s they be altered after their creation. Let's see them in action to see what I mean: 

In [47]:
# A dictionary of Student Heights in cm
student_heights = {'Jack': 170.0, 'Jill': 180.0, 'Mark': 165.0, 'Jen':170.0}

# Print dictionary of student heights
print(student_heights)

{'Jack': 170.0, 'Jill': 180.0, 'Mark': 165.0, 'Jen': 170.0}


In [51]:
print('Jack\'s height: ', student_heights['Jack'],'cm')
print('Jill\'s height: ', student_heights['Jill'],'cm')
print('Mark\'s height: ', student_heights['Mark'],'cm')
print('Jen\'s height: ' , student_heights['Jen'],'cm')

Jack's height:  170.0 cm
Jill's height:  180.0 cm
Mark's height:  165.0 cm
Jen's height:  170.0 cm


In [54]:
# lets say we have a new student, Erik. We can add their infromation to our dictionary
student_heights['Erik'] = 175.0
# Print added key's value
print('Eriks\'s height: ' , student_heights['Erik'],'cm')

Eriks's height:  175.0 cm


It's important to note that the _values_ associated with a key within a `dictionary` don't have to be just _floats_. They can be _strings_, _integers_, _list_, _tuples_, or even `numpy.arrays`. 

In [57]:
Mean_annual_temp = {'station_1': [0., 1., 0., 3., 5.], 
                    'station_2': [1., 3., 4., 5., 3.],
                    'station_3': [0., 0., 1., 2., 0.],
                   }

In [60]:
type(Mean_annual_temp['station_1'])

list

# Intro to NumPy Arrays 

In [3]:
import numpy as np 

In [4]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [64]:
x = np.arange(1,6)
print(x)

[1 2 3 4 5]


In [66]:
print('x is of shape: ',x.shape)

x is of shape:  (5,)


In [69]:
x.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [21]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

`range` and `np.arange` take `start`, `stop`+1, and `stride` as their arguments.

In [22]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## Indexing 

We can select elements, rows, and columns of NumPy arrays (and other data structures as well). 

In [18]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
A = np.arange(1,26).reshape(5,5)

In [20]:
# Get the top left emlment of A
print('Top left:', A[0,0])
# Get the top right emlment of A
print('Top left:', A[0,4])
# Get the bottom left emlment of A
print('Top left:', A[4,0])
# Get the bottom right emlment of A
print('Top left:', A[4,4])

Top left: 1
Top left: 5
Top left: 21
Top left: 25


In [36]:
import pprint
# Get the first column of A
print('Column One:')
pprint.pprint(A[:,0].reshape(5,1))

# Get the first row of A
print('Column One:')
pprint.pprint(A[0,:])

Column One:
array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])
Column One:
array([1, 2, 3, 4, 5])


In [39]:
# Get the first two columns of A
print('Column One and two:')
pprint.pprint(A[:,0:2])

Column One and two:
array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22]])
