# Lab 1: Intro to `python` 

__01/21__   

Andrew (he/him): anolan@sfu.ca  



# `numpy` refresher: 
  * [Indexing and slicing](#indexing) 
  * [Array operations](#array_ops) 
  * [Broadcasting](#broadcasting)
  * [More Array operations](#array_methods) 
  
  
_Note_: All of the `numpy` example come from [here](https://numpy.org/doc/stable/user/absolute_beginners.html). Keep track of this link as it will be a useful reference. Also, the headings of all the `numpy` subsection are hyperlinks to the respective topics on the `numpy` doc page. 

## [Indexing and slicing](https://numpy.org/doc/stable/user/absolute_beginners.html#indexing-and-slicing)  <a class="anchor" id="indexing"></a>

In [40]:
import numpy as np 
data = np.array([1,2,3])
#Get the first element 
data[0]
#Get the second element 
data[1]
# Get the first two elements 
data[0:2]
# Get the second two elements 
data[1:]

array([2, 3])

<img src="https://numpy.org/doc/stable/_images/np_indexing.png" alt="anatomy" width="800" height="800">

## [Array operations](https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations)  <a class="anchor" id="array_ops"></a>

In [41]:
import numpy as np 
# Create a (2,) array
data = np.array([1, 2])

ones = np.ones(shape=2, dtype=int)

<img src="https://numpy.org/doc/stable/_images/np_array_dataones.png" alt="anatomy" width="800" height="800">

In [42]:
data + ones 

array([2, 3])

<img src="https://numpy.org/doc/stable/_images/np_data_plus_ones.png" alt="anatomy" width="800" height="800">

## [Array operations part 2](https://numpy.org/doc/stable/user/absolute_beginners.html#basic-array-operations)

In [43]:
print(data - ones)

print(data * data)

print(data / data)

[0 1]
[1 4]
[1. 1.]


<img src="https://numpy.org/doc/stable/_images/np_sub_mult_divide.png" alt="anatomy" width="800" height="800">

## [Broadcasting](https://numpy.org/doc/stable/user/absolute_beginners.html#broadcasting)  <a class="anchor" id="broadcasting"></a>

In [44]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

<img src="https://numpy.org/doc/stable/_images/np_multiply_broadcasting.png" alt="anatomy" width="800" height="800">

## [More Array Operations](https://numpy.org/doc/stable/user/absolute_beginners.html#more-useful-array-operations) <a class="anchor" id="array_methods"></a>

In [1]:
data = np.array([1,2,3])


print(data.max())

print(data.min())

print(data.sum())


NameError: name 'np' is not defined

<img src="https://numpy.org/doc/stable/_images/np_aggregation.png" alt="anatomy" width="800" height="800">

# Control flow:  
  * [`for` loops](#)
  * [`if`, `elif`, `else` statements](#)

## `for` loops  

Iterate over a sequence. Allow you to repeat an operation multiple times. 

In [46]:
for i in [1,2,3]:
    print('i = ', i)

i =  1
i =  2
i =  3


In [47]:
for element in ['element1','element2','element3']:
    print('element = ',element)

element =  element1
element =  element2
element =  element3


__Lets iterate over all the elements in a matrix__

In [48]:
array = np.arange(1,10).reshape(3,3)

array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
m,n = array.shape

In [50]:
for row in range(m):
    for col in range(n):
        print('Row :',row,' Col :', col, ' array[{},{}]: {}'.format(row,col,array[row,col]))

Row : 0  Col : 0  array[0,0]: 1
Row : 0  Col : 1  array[0,1]: 2
Row : 0  Col : 2  array[0,2]: 3
Row : 1  Col : 0  array[1,0]: 4
Row : 1  Col : 1  array[1,1]: 5
Row : 1  Col : 2  array[1,2]: 6
Row : 2  Col : 0  array[2,0]: 7
Row : 2  Col : 1  array[2,1]: 8
Row : 2  Col : 2  array[2,2]: 9


## `if` statements: 

- `if` condition following `if` statement is true then the code within the `if` statement is evaluated.   

In [51]:
a = 5.0
b = 10.0
c = 15.0

a < b

True

In [57]:
if a < b: 
    print('Condition 1 is True, a<b')

Condition 1 is True, a<b


- `if` condition following `if` statement is true then the code within the `if` statement is evaluated.   

- `elif` follows an `if` and is evaluated only if above `if` is `False`.


In [58]:
a = 5.0
b = 10.0
c = 15.0

if a < b: 
    print('Condition 1 is True, a<b')
if b < c:
    print('Condition 2 is True, b<c')

Condition 1 is True, a<b
Condition 2 is True, b<c


In [63]:
if a < b: 
    print('Condition 1 is True, b<a')
elif b < c:
    print('Condition 2 is True, b<c')

Condition 1 is True, b<a


- `if` condition following `if` statement is true then the code within the `if` statement is evaluated.   

- `elif` follows an `if` and is evaluated only if above `if` is `False`.

- `else` is none of the conditions are `True`, then execute code within `else`.

In [55]:
a = 5.0
b = 10.0
c = 15.0

if a > b: 
    print('Condition 1 is True, a>b')
elif b > c:
    print('Condition 2 is True, b>c')
else:
    print('None of the above conditions are True')

None of the above conditions are True


## `for` loops and `if` statements 

Lets create a new 3 x 3 array, like before, but all of odd elements are NaNs (Not a Number) by using `np.nan` for NaN. 

- First, recreate our array from before
- Second, make an empty array which will be only evens and everything else will be `np.nan`. 

In [80]:
import numpy as np 

array = np.arange(1,10,dtype=np.float).reshape(3,3)

print('array:')
print(array)

evens = np.ones((3,3),dtype=np.float)

print('\nevens:')
print(evens)

array:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

evens:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [62]:
# HOW WOULD YOU SOLVE THIS??
